---
abstract: 'More Liberal HTML Head Section Parsing'
author:
  - 'Daisuke Maki <lestrrat>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-HeadParser-Liberal
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  HTML::HeadParser::Liberal:
    file: lib/HTML/HeadParser/Liberal.pm
    version: 0.01
requires:
  B::Deparse: 0
  HTML::HeadParser: '== 3.69'
  perl: 5.008005
resources:
  bugtracker: https://github.com/lestrrat/p5-HTML-HeadParser-Liberal/issues
  homepage: https://github.com/lestrrat/p5-HTML-HeadParser-Liberal
  repository: git://github.com/lestrrat/p5-HTML-HeadParser-Liberal.git
version: 0.01
x_contributors:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
